# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables:
  NodeVersion: "14.x"

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  displayName: Build
  jobs:
  - job: npmBuild
    displayName: npm build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: "$(NodeVersion)"
      displayName: 'Install Node.js'

    - script: |
        npm ci
        npm run build
      displayName: 'npm install and build'
    
    - publish: $(Build.SourcesDirectory)/dist
      artifact: dist
- stage: test
  displayName: Test
  jobs:
  - job: unit
    displayName: Unit Tests
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: "$(NodeVersion)"
      displayName: 'Install Node.js'
    
    - download: current
      
    - script: |
        npm ci
        npm run test
      displayName: 'npm install and test'
